export const albums = [
  {
    id: 1,
    title: "L.I.F.E",
    year: "August 12, 2013",
    tracks: 17,
    genre: "Afrobeat, Ragga, Dancehall, Fuji",
    streams: "37 M",
    image: "/albums/album-1.jpg",
    url: "https://open.spotify.com/album/7pqUKMWH6P7AJPIjUiphTS",
  },
  {
    id: 2,
    title: "On a Spaceship",
    year: "November 16, 2015",
    tracks: 14,
    genre: "Afrobeats, Afro-fusion",
    streams: "42.8 M",
    image: "/albums/album-2.webp",
    url: "https://open.spotify.com/album/5zH79s5J4D633IxoFWadp8",
  },
  {
    id: 3,
    title: "Outside",
    year: "January 26, 2018",
    tracks: 15,
    genre: "Afrobeats, Reggae, Dancehall",
    streams: "430 M",
    image: "/albums/album-3.jpg",
    url: "https://open.spotify.com/album/5SCK5p3Rqgg0FwTmAurrcp",
  },
  {
    id: 4,
    title: "African Giant",
    year: "July 26, 2019",
    tracks: 17,
    genre: "Afrobeats, Dancehall, Pop, Hip-hop",
    streams: "1.114 B",
    image: "/albums/album-4.jpg",
    url: "https://open.spotify.com/album/79lrrUvUyIuOD12b5taQVP",
  },
  {
    id: 5,
    title: "Twice as Tall",
    year: "August 14, 2020",
    tracks: 14,
    genre: "Afrobeats, Dancehall, Pop, Hip-hop",
    streams: "357.4 M",
    image: "/albums/album-5.jpg",
    url: "https://open.spotify.com/album/4moiYbxseWbPD2moVhOYje",
  },
  {
    id: 6,
    title: "Love, Damini",
    year: "July 8, 2022",
    tracks: 16,
    genre: "Afro-fusion",
    streams: "1.435 B",
    image: "/albums/album-6.jpg",
    url: "https://open.spotify.com/album/6kgDkAupBVRSqbJPUaTJwQ",
  },
  {
    id: 7,
    title: "I Told Them...",
    year: "August 25, 2023",
    tracks: 13,
    genre: "Afro-fusion, Afrobeats, Hip-hop",
    streams: "701.5 M",
    image: "/albums/album-7.jpg",
    url: "https://open.spotify.com/album/1JzjwUKkPsdHg1SQ7qa5hc",
  },
  {
    id: 8,
    title: "No Sign of Weakness",
    year: "July 11, 2025",
    tracks: 16,
    genre: "Afrobeats, Rock, Funk, Country, Electronic",
    streams: "134.6 M",
    image: "/albums/album-8.jpg",
    url: "https://open.spotify.com/album/35EMM8QwKJ2qXmoUJnUSNf",
  },
];
export const tourDates = [
  {
    id: 1,
    date: "2025-11-12",
    city: "Morrison",
    country: "USA",
    venue: "Red Rocks Amphitheatre",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
    special: "First Nigerian artist to headline Red Rocks",
  },
  {
    id: 2,
    date: "2025-11-14",
    city: "Los Angeles",
    country: "USA",
    venue: "Crypto.com Arena",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 3,
    date: "2025-11-16",
    city: "San Francisco",
    country: "USA",
    venue: "Chase Center",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 4,
    date: "2025-11-18",
    city: "Portland",
    country: "USA",
    venue: "Moda Center",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 5,
    date: "2025-11-19",
    city: "Inglewood",
    country: "USA",
    venue: "Kia Forum",
    status: "few-left",
    ticketUrl:
      "https://www.ticketmaster.com/burna-boy-no-sign-of-weakness-inglewood-california-11-19-2025/event/090062CABD732B4B",
  },
  {
    id: 6,
    date: "2025-11-21",
    city: "Phoenix",
    country: "USA",
    venue: "Footprint Center",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 7,
    date: "2025-11-24",
    city: "Houston",
    country: "USA",
    venue: "Toyota Center",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 8,
    date: "2025-11-26",
    city: "Dallas",
    country: "USA",
    venue: "American Airlines Center",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 9,
    date: "2025-11-28",
    city: "Chicago",
    country: "USA",
    venue: "United Center",
    status: "few-left",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 10,
    date: "2025-12-01",
    city: "Atlanta",
    country: "USA",
    venue: "State Farm Arena",
    status: "available",
    ticketUrl: "https://www.statefarmarena.com/events/detail/burna-boy-2025",
  },
  {
    id: 11,
    date: "2025-12-03",
    city: "Miami",
    country: "USA",
    venue: "FTX Arena",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 12,
    date: "2025-12-05",
    city: "Washington",
    country: "USA",
    venue: "Capital One Arena",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 13,
    date: "2025-12-06",
    city: "Philadelphia",
    country: "USA",
    venue: "Wells Fargo Center",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 14,
    date: "2025-12-08",
    city: "New York",
    country: "USA",
    venue: "Madison Square Garden",
    status: "few-left",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 15,
    date: "2025-12-10",
    city: "Boston",
    country: "USA",
    venue: "TD Garden",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 16,
    date: "2025-12-12",
    city: "Detroit",
    country: "USA",
    venue: "Little Caesars Arena",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 17,
    date: "2025-12-17",
    city: "Toronto",
    country: "Canada",
    venue: "Scotiabank Arena",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
  },
  {
    id: 18,
    date: "2025-12-18",
    city: "Toronto",
    country: "Canada",
    venue: "Scotiabank Arena",
    status: "available",
    ticketUrl: "https://www.ticketmaster.com/burna-boy-tickets/artist/2486272",
    special: "Final show of North American leg",
  },
];
export const merchItems = [
  {
    id: 1,
    name: "African Giant Anniversary T-Shirt",
    image: "/merchs/African Giant Anniversary T-Shirt.webp",
    price: "₦12,000",
    originalPrice: "₦15,000",
    category: "Apparel",
    bestseller: true,
  },
  {
    id: 2,
    name: "I Told Them... Fan Pack",
    image: "/merchs/I told them... Fan Pack.webp",
    price: "₦7,000",
    category: "Accessories",
  },
  {
    id: 3,
    name: "African Giant Anniversary T-Shirt",
    image: "/merchs/African Giant Anniversary T-Shirt.webp",
    price: "₦25,000",
    category: "Apparel",
    limited: true,
  },
  {
    id: 4,
    name: "I told them... T-Shirt",
    image: "/merchs/I told them... T-Shirt.webp",
    price: "₦18,000",
    originalPrice: "₦22,000",
    category: "Apparel",
    bestseller: true,
  },
  {
    id: 5,
    name: "Love, Damini Tee",
    image: "/merchs/Love, Damini Tee.webp",
    price: "₦4,500",
    category: "Apparel",
  },
  {
    id: 6,
    name: "I told them... Vinyl",
    image: "/merchs/I told them... Vinyl.webp",
    price: "₦3,000",
    category: "Art",
  },
  {
    id: 7,
    name: "Twice As Tall Exclusive Red Vinyl",
    image: "/merchs/Twice As Tall Exclusive Red Vinyl.webp",
    price: "₦6,500",
    category: "Art",
  },
  {
    id: 8,
    name: "Twice As Tall T-Shirt(Black)",
    image: "/merchs/Twice As Tall T-Shirt(Black).webp",
    price: "₦8,000",
    category: "Accessories",
    limited: true,
  },
  {
    id: 9,
    name: "No Sign Of Weakness Vinyl",
    image: "/merchs/No Sign Of Weakness Vinyl.webp",
    price: "₦8,000",
    category: "Art",
    bestseller: true,
  },
  {
    id: 10,
    name: "Love, Damini Vinyl",
    image: "/merchs/Love, Damini Vinyl.webp",
    price: "₦8,000",
    category: "Art",
  },
];
